cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: A
      secret-key: z7iW
spring:
  data:
    mongodb:
      uri: mongodb://admin:cpass____@server:27017/dev?authSource=admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: ad
    password: fb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true